import {
  A11yCheckerPlugin,
  AnchorPlugin,
  ApprovalWorkflowPlugin,
  BackgroundColorPlugin,
  BlockquotePlugin,
  BlocksLibraryPlugin,
  BoldPlugin,
  CapitalizationPlugin,
  ChecklistPlugin,
  CitationsPlugin,
  ClearFormattingPlugin,
  CodePlugin,
  CodeSamplePlugin,
  CommentsPlugin,
  ConditionalContentPlugin,
  ContentRulesPlugin,
  DataBindingPlugin,
  DirectionPlugin,
  DocSchemaPlugin,
  DocumentManagerPlugin,
  EmbedIframePlugin,
  EmojisPlugin,
  FontFamilyPlugin,
  FontSizePlugin,
  FootnotePlugin,
  FullscreenPlugin,
  HeadingPlugin,
  HistoryPlugin,
  IndentPlugin,
  ItalicPlugin,
  LineHeightPlugin,
  LinkPlugin,
  ListPlugin,
  MathPlugin,
  MediaManagerPlugin,
  MentionPlugin,
  MergeTagPlugin,
  PageBreakPlugin,
  PIIRedactionPlugin,
  PreviewPlugin,
  PrintPlugin,
  SlashCommandsPlugin,
  SmartPastePlugin,
  SpecialCharactersPlugin,
  SpellCheckPlugin,
  StrikethroughPlugin,
  TablePlugin,
  TemplatePlugin,
  TextAlignmentPlugin,
  TextColorPlugin,
  TrackChangesPlugin,
  TranslationWorkflowPlugin,
  UnderlinePlugin,
  VersionDiffPlugin,
} from '@editora/plugins';

export const allNativePlugins = [
  BoldPlugin(),
  ItalicPlugin(),
  UnderlinePlugin(),
  StrikethroughPlugin(),
  ClearFormattingPlugin(),
  HeadingPlugin(),
  BlockquotePlugin(),
  CodePlugin(),
  CodeSamplePlugin(),
  ListPlugin(),
  ChecklistPlugin(),
  TextAlignmentPlugin(),
  IndentPlugin(),
  DirectionPlugin(),
  TextColorPlugin(),
  BackgroundColorPlugin(),
  FontSizePlugin(),
  FontFamilyPlugin(),
  LineHeightPlugin(),
  CapitalizationPlugin(),
  LinkPlugin(),
  TablePlugin(),
  AnchorPlugin(),
  EmbedIframePlugin(),
  MathPlugin(),
  MediaManagerPlugin(),
  MergeTagPlugin(),
  PageBreakPlugin(),
  PrintPlugin(),
  PreviewPlugin(),
  SpecialCharactersPlugin(),
  SpellCheckPlugin(),
  EmojisPlugin(),
  A11yCheckerPlugin(),
  CommentsPlugin(),
  DocumentManagerPlugin(),
  FullscreenPlugin(),
  TemplatePlugin(),
  HistoryPlugin(),
  FootnotePlugin(),
  TrackChangesPlugin(),
  VersionDiffPlugin(),
  ConditionalContentPlugin(),
  DataBindingPlugin({
    data: {
      user: { firstName: 'Ava', lastName: 'Miller' },
      order: { total: 1234.56, createdAt: '2026-03-03T12:00:00Z' },
    },
  }),
  ContentRulesPlugin({
    bannedWords: ['obviously', 'simply'],
    requiredHeadings: ['Summary'],
    maxSentenceWords: 28,
    minReadabilityScore: 55,
    enableRealtime: true,
  }),
  CitationsPlugin({
    defaultStyle: 'apa',
    enableFootnoteSync: true,
  }),
  ApprovalWorkflowPlugin({
    defaultStatus: 'draft',
    lockOnApproval: true,
    defaultActor: 'Editorial Lead',
  }),
  PIIRedactionPlugin({
    enableRealtime: true,
    redactionMode: 'token',
    maxFindings: 120,
  }),
  SmartPastePlugin({
    defaultProfile: 'balanced',
    maxHtmlLength: 220000,
  }),
  BlocksLibraryPlugin({
    maxResults: 120,
    blocks: [
      {
        id: 'incident-summary',
        label: 'Incident Summary Block',
        category: 'Operations',
        tags: ['incident', 'summary'],
        keywords: ['postmortem', 'rca'],
        html: '<h3>Incident Summary</h3><p>Describe impact, timeline, and customer exposure.</p>',
      },
      {
        id: 'risk-register-entry',
        label: 'Risk Register Entry',
        category: 'Compliance',
        tags: ['risk', 'governance'],
        keywords: ['mitigation', 'owner'],
        html: '<h3>Risk Register Entry</h3><p><strong>Risk:</strong> <em>Describe risk here.</em></p><p><strong>Mitigation:</strong> Define mitigation owner and due date.</p>',
      },
      {
        id: 'release-rollback',
        label: 'Release Rollback Plan',
        category: 'Engineering',
        tags: ['release', 'rollback'],
        keywords: ['deployment', 'runbook'],
        html: '<h3>Rollback Plan</h3><ol><li>Pause rollout</li><li>Revert deployment</li><li>Validate service health</li></ol>',
      },
    ],
  }),
  DocSchemaPlugin({
    defaultSchemaId: 'policy',
    enableRealtime: true,
    schemas: [
      {
        id: 'policy',
        label: 'Policy',
        strictOrder: true,
        allowUnknownHeadings: true,
        sections: [
          { title: 'Policy Statement' },
          { title: 'Applicability', aliases: ['Scope'] },
          { title: 'Controls' },
          { title: 'Exceptions' },
          { title: 'Enforcement' },
        ],
      },
    ],
  }),
  TranslationWorkflowPlugin({
    sourceLocale: 'en-US',
    targetLocale: 'fr-FR',
    enableRealtime: true,
    locales: ['en-US', 'fr-FR', 'de-DE', 'es-ES', 'ja-JP'],
  }),
  SlashCommandsPlugin(),
  MentionPlugin({
    items: [
      { id: 'john.doe', label: 'John Doe', meta: 'john@acme.com' },
      { id: 'sarah.lee', label: 'Sarah Lee', meta: 'sarah@acme.com' },
      { id: 'ops.team', label: 'Ops Team', meta: 'team' },
    ],
  }),
];

