import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Grouped into 6 top-level sections instead of 16 flat categories.
 * Mirrors how a developer actually adopts the ecosystem:
 * orient → install the editor → style it → build UI around it → look things up.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",

    {
      type: "category",
      label: "Start",
      collapsed: false,
      items: [
        { type: "autogenerated", dirName: "getting-started" },
        "ai-usage",
        "editora-prompts",
      ],
    },

    {
      type: "category",
      label: "Editor",
      link: { type: "generated-index", title: "Editor Packages" },
      items: [
        { type: "autogenerated", dirName: "editor" },
        { type: "autogenerated", dirName: "plugins" },
      ],
    },

    {
      type: "category",
      label: "UI Kit",
      link: { type: "generated-index", title: "UI Kit" },
      items: [
        { type: "autogenerated", dirName: "ui-react" },
        { type: "autogenerated", dirName: "ui-core" },
        { type: "autogenerated", dirName: "icons" },
        { type: "autogenerated", dirName: "react-icons" },
        { type: "autogenerated", dirName: "toast" },
      ],
    },

    {
      type: "category",
      label: "Customize",
      link: { type: "generated-index", title: "Customize" },
      items: [
        { type: "autogenerated", dirName: "theming" },
        { type: "autogenerated", dirName: "guide" },
        { type: "autogenerated", dirName: "advanced" },
      ],
    },

    {
      type: "category",
      label: "Examples",
      link: { type: "generated-index", title: "Examples" },
      items: [{ type: "autogenerated", dirName: "examples" }],
    },

    {
      type: "category",
      label: "Reference",
      link: { type: "generated-index", title: "Reference" },
      items: [
        { type: "autogenerated", dirName: "reference" },
        { type: "autogenerated", dirName: "packages" },
        { type: "autogenerated", dirName: "migration" },
        { type: "autogenerated", dirName: "contributing" },
      ],
    },
  ],
};

export default sidebars;
