type CharacterCategory =
  | "all"
  | "currency"
  | "text"
  | "quotation"
  | "mathematical"
  | "extended-latin"
  | "symbols"
  | "arrows";

const characterSets: Record<
  CharacterCategory,
  { name: string; characters: string[] }
> = {
  all: {
    name: "All",
    characters: [
      "€",
      "£",
      "¥",
      "¢",
      "₹",
      "₽",
      "₩",
      "₿",
      "₺",
      "₴",
      "₦",
      "₨",
      "₪",
      "₫",
      "₭",
      "₮",
      "₯",
      "₰",
      "₱",
      "₲",
      "₳",
      "₴",
      "₵",
      "₶",
      "₷",
      "₹",
      "₺",
      "₼",
      "₽",
      "₾",
      "₿",
      '"',
      "'",
      "«",
      "»",
      "„",
      "‟",
      "‹",
      "›",
      "‚",
      "‛",
      "〝",
      "〞",
      "〟",
      "‟",
      "„",
      "©",
      "®",
      "™",
      "°",
      "§",
      "¶",
      "†",
      "‡",
      "•",
      "‣",
      "⁃",
      "‰",
      "‱",
      "′",
      "″",
      "‴",
      "‵",
      "‶",
      "‷",
      "※",
      "‼",
      "‽",
      "‾",
      "‿",
      "⁀",
      "⁁",
      "⁂",
      "⁃",
      "⁇",
      "⁈",
      "⁉",
      "+",
      "-",
      "×",
      "÷",
      "=",
      "≠",
      "≈",
      "≡",
      "≤",
      "≥",
      "<",
      ">",
      "±",
      "∓",
      "∴",
      "∵",
      "∶",
      "∷",
      "∸",
      "∹",
      "∺",
      "∻",
      "∼",
      "∽",
      "∾",
      "∿",
      "≀",
      "≁",
      "≂",
      "≃",
      "≄",
      "≅",
      "≆",
      "≇",
      "≈",
      "≉",
      "≊",
      "≋",
      "≌",
      "≍",
      "≎",
      "≏",
      "≐",
      "≑",
      "≒",
      "≓",
      "≔",
      "≕",
      "≖",
      "≗",
      "≘",
      "≙",
      "≚",
      "≛",
      "≜",
      "≝",
      "≞",
      "≟",
      "≠",
      "≡",
      "≢",
      "≣",
      "≤",
      "≥",
      "≦",
      "≧",
      "≨",
      "≩",
      "≪",
      "≫",
      "≬",
      "≭",
      "≮",
      "≯",
      "≰",
      "≱",
      "≲",
      "≳",
      "≴",
      "≵",
      "≶",
      "≷",
      "≸",
      "≹",
      "≺",
      "≻",
      "≼",
      "≽",
      "≾",
      "≿",
      "À",
      "Á",
      "Â",
      "Ã",
      "Ä",
      "Å",
      "Æ",
      "Ç",
      "È",
      "É",
      "Ê",
      "Ë",
      "Ì",
      "Í",
      "Î",
      "Ï",
      "Ð",
      "Ñ",
      "Ò",
      "Ó",
      "Ô",
      "Õ",
      "Ö",
      "×",
      "Ø",
      "Ù",
      "Ú",
      "Û",
      "Ü",
      "Ý",
      "Þ",
      "ß",
      "à",
      "á",
      "â",
      "ã",
      "ä",
      "å",
      "æ",
      "ç",
      "è",
      "é",
      "ê",
      "ë",
      "ì",
      "í",
      "î",
      "ï",
      "ð",
      "ñ",
      "ò",
      "ó",
      "ô",
      "õ",
      "ö",
      "÷",
      "ø",
      "ù",
      "ú",
      "û",
      "ü",
      "ý",
      "þ",
      "ÿ",
      "¡",
      "¿",
      "‽",
      "‼",
      "⁇",
      "⁈",
      "⁉",
      "‽",
      "※",
      "‾",
      "‿",
      "⁀",
      "⁁",
      "⁂",
      "⁃",
      "⁇",
      "⁈",
      "⁉",
      "←",
      "↑",
      "→",
      "↓",
      "↔",
      "↕",
      "↖",
      "↗",
      "↘",
      "↙",
      "↚",
      "↛",
      "↜",
      "↝",
      "↞",
      "↟",
      "↠",
      "↡",
      "↢",
      "↣",
      "↤",
      "↥",
      "↦",
      "↧",
      "↨",
      "↩",
      "↪",
      "↫",
      "↬",
      "↭",
      "↮",
      "↯",
      "↰",
      "↱",
      "↲",
      "↳",
      "↴",
      "↵",
      "↶",
      "↷",
      "↸",
      "↹",
      "↺",
      "↻",
      "↼",
      "↽",
      "↾",
      "↿",
      "⇀",
      "⇁",
      "⇂",
      "⇃",
      "⇄",
      "⇅",
      "⇆",
      "⇇",
      "⇈",
      "⇉",
      "⇊",
      "⇋",
      "⇌",
      "⇍",
      "⇎",
      "⇏",
      "⇐",
      "⇑",
      "⇒",
      "⇓",
      "⇔",
      "⇕",
      "⇖",
      "⇗",
      "⇘",
      "⇙",
      "⇚",
      "⇛",
      "⇜",
      "⇝",
      "⇞",
      "⇟",
      "⇠",
      "⇡",
      "⇢",
      "⇣",
      "⇤",
      "⇥",
      "⇦",
      "⇧",
      "⇨",
      "⇩",
      "⇪",
      "⇫",
      "⇬",
      "⇭",
      "⇮",
      "⇯",
      "⇰",
      "⇱",
      "⇲",
      "⇳",
      "⇴",
      "⇵",
      "⇶",
      "⇷",
      "⇸",
      "⇹",
      "⇺",
      "⇻",
      "⇼",
      "⇽",
      "⇾",
      "⇿",
    ],
  },
  currency: {
    name: "Currency",
    characters: [
      "€",
      "£",
      "¥",
      "¢",
      "₹",
      "₽",
      "₩",
      "₿",
      "₺",
      "₴",
      "₦",
      "₨",
      "₪",
      "₫",
      "₭",
      "₮",
      "₯",
      "₰",
      "₱",
      "₲",
      "₳",
      "₵",
      "₶",
      "₷",
      "₼",
      "₾",
      "₿",
    ],
  },
  text: {
    name: "Text",
    characters: [
      "©",
      "®",
      "™",
      "°",
      "§",
      "¶",
      "†",
      "‡",
      "•",
      "‣",
      "⁃",
      "‰",
      "‱",
      "′",
      "″",
      "‴",
      "‵",
      "‶",
      "‷",
      "※",
      "‼",
      "‽",
      "‾",
      "‿",
      "⁀",
      "⁁",
      "⁂",
    ],
  },
  quotation: {
    name: "Quotation",
    characters: [
      '"',
      "'",
      "«",
      "»",
      "„",
      "‟",
      "‹",
      "›",
      "‚",
      "‛",
      "〝",
      "〞",
      "〟",
      "‟",
      "„",
    ],
  },
  mathematical: {
    name: "Mathematical",
    characters: [
      "+",
      "-",
      "×",
      "÷",
      "=",
      "≠",
      "≈",
      "≡",
      "≤",
      "≥",
      "<",
      ">",
      "±",
      "∓",
      "∴",
      "∵",
      "∶",
      "∷",
      "∸",
      "∹",
      "∺",
      "∻",
      "∼",
      "∽",
      "∾",
      "∿",
      "≀",
      "≁",
      "≂",
      "≃",
      "≄",
      "≅",
      "≆",
      "≇",
      "≈",
      "≉",
      "≊",
      "≋",
      "≌",
      "≍",
      "≎",
      "≏",
      "≐",
      "≑",
      "≒",
      "≓",
      "≔",
      "≕",
      "≖",
      "≗",
      "≘",
      "≙",
      "≚",
      "≛",
      "≜",
      "≝",
      "≞",
      "≟",
      "≠",
      "≡",
      "≢",
      "≣",
      "≤",
      "≥",
      "≦",
      "≧",
      "≨",
      "≩",
      "≪",
      "≫",
      "≬",
      "≭",
      "≮",
      "≯",
      "≰",
      "≱",
      "≲",
      "≳",
      "≴",
      "≵",
      "≶",
      "≷",
      "≸",
      "≹",
      "≺",
      "≻",
      "≼",
      "≽",
      "≾",
      "≿",
    ],
  },
  "extended-latin": {
    name: "Extended Latin",
    characters: [
      "À",
      "Á",
      "Â",
      "Ã",
      "Ä",
      "Å",
      "Æ",
      "Ç",
      "È",
      "É",
      "Ê",
      "Ë",
      "Ì",
      "Í",
      "Î",
      "Ï",
      "Ð",
      "Ñ",
      "Ò",
      "Ó",
      "Ô",
      "Õ",
      "Ö",
      "×",
      "Ø",
      "Ù",
      "Ú",
      "Û",
      "Ü",
      "Ý",
      "Þ",
      "ß",
      "à",
      "á",
      "â",
      "ã",
      "ä",
      "å",
      "æ",
      "ç",
      "è",
      "é",
      "ê",
      "ë",
      "ì",
      "í",
      "î",
      "ï",
      "ð",
      "ñ",
      "ò",
      "ó",
      "ô",
      "õ",
      "ö",
      "÷",
      "ø",
      "ù",
      "ú",
      "û",
      "ü",
      "ý",
      "þ",
      "ÿ",
    ],
  },
  symbols: {
    name: "Symbols",
    characters: [
      "¡",
      "¿",
      "‽",
      "‼",
      "⁇",
      "⁈",
      "⁉",
      "※",
      "‾",
      "‿",
      "⁀",
      "⁁",
      "⁂",
      "⁃",
    ],
  },
  arrows: {
    name: "Arrows",
    characters: [
      "←",
      "↑",
      "→",
      "↓",
      "↔",
      "↕",
      "↖",
      "↗",
      "↘",
      "↙",
      "↚",
      "↛",
      "↜",
      "↝",
      "↞",
      "↟",
      "↠",
      "↡",
      "↢",
      "↣",
      "↤",
      "↥",
      "↦",
      "↧",
      "↨",
      "↩",
      "↪",
      "↫",
      "↬",
      "↭",
      "↮",
      "↯",
      "↰",
      "↱",
      "↲",
      "↳",
      "↴",
      "↵",
      "↶",
      "↷",
      "↸",
      "↹",
      "↺",
      "↻",
      "↼",
      "↽",
      "↾",
      "↿",
      "⇀",
      "⇁",
      "⇂",
      "⇃",
      "⇄",
      "⇅",
      "⇆",
      "⇇",
      "⇈",
      "⇉",
      "⇊",
      "⇋",
      "⇌",
      "⇍",
      "⇎",
      "⇏",
      "⇐",
      "⇑",
      "⇒",
      "⇓",
      "⇔",
      "⇕",
      "⇖",
      "⇗",
      "⇘",
      "⇙",
      "⇚",
      "⇛",
      "⇜",
      "⇝",
      "⇞",
      "⇟",
      "⇠",
      "⇡",
      "⇢",
      "⇣",
      "⇤",
      "⇥",
      "⇦",
      "⇧",
      "⇨",
      "⇩",
      "⇪",
      "⇫",
      "⇬",
      "⇭",
      "⇮",
      "⇯",
      "⇰",
      "⇱",
      "⇲",
      "⇳",
      "⇴",
      "⇵",
      "⇶",
      "⇷",
      "⇸",
      "⇹",
      "⇺",
      "⇻",
      "⇼",
      "⇽",
      "⇾",
      "⇿",
    ],
  },
};

      const descriptions: Record<string, string> = {
        // Currency symbols
        "€": "euro",
        "£": "pound sterling",
        "¥": "yen",
        "¢": "cent",
        "₹": "rupee",
        "₽": "ruble",
        "₩": "won",
        "₿": "bitcoin",
        "₺": "lira",
        "₴": "hryvnia",
        "₦": "naira",
        "₨": "rupee",
        "₪": "shekel",
        "₫": "dong",
        "₭": "kip",
        "₮": "tugrik",
        "₯": "drachma",
        "₰": "german penny",
        "₱": "peso",
        "₲": "guarani",
        "₳": "austral",
        "₵": "cedi",
        "₶": "livre tournois",
        "₷": "spesmilo",
        "₼": "manat",
        "₾": "lari",

        // Quotation marks
        '"': "quotation mark",
        "'": "apostrophe",
        "«": "left double angle quote",
        "»": "right double angle quote",
        "„": "double low quotation mark",
        "‟": "double high reversed quotation mark",
        "‹": "left single angle quote",
        "›": "right single angle quote",
        "‚": "single low quotation mark",
        "‛": "single high reversed quotation mark",
        "〝": "reversed double prime quotation mark",
        "〞": "double prime quotation mark",
        "〟": "low double prime quotation mark",

        // Text symbols
        "©": "copyright",
        "®": "registered",
        "™": "trademark",
        "°": "degree",
        "§": "section",
        "¶": "paragraph",
        "†": "dagger",
        "‡": "double dagger",
        "•": "bullet",
        "‣": "triangular bullet",
        "⁃": "hyphen bullet",
        "‰": "per mille",
        "‱": "per ten thousand",
        "′": "prime",
        "″": "double prime",
        "‴": "triple prime",
        "‵": "reversed prime",
        "‶": "reversed double prime",
        "‷": "reversed triple prime",
        "※": "reference mark",
        "‼": "double exclamation mark",
        "‽": "interrobang",
        "‾": "overline",
        "‿": "undertie",
        "⁀": "character tie",
        "⁁": "caret insertion point",
        "⁂": "asterism",
        "⁇": "double question mark",
        "⁈": "question exclamation mark",
        "⁉": "exclamation question mark",

        // Mathematical operators
        "+": "plus",
        "-": "minus",
        "×": "multiplication",
        "÷": "division",
        "=": "equals",
        "≠": "not equal",
        "≈": "approximately equal",
        "≡": "identical to",
        "≤": "less than or equal",
        "≥": "greater than or equal",
        "<": "less than",
        ">": "greater than",
        "±": "plus minus",
        "∓": "minus plus",
        "∴": "therefore",
        "∵": "because",
        "∶": "ratio",
        "∷": "proportion",
        "∸": "dot minus",
        "∹": "excess",
        "∺": "geometric proportion",
        "∻": "homothetic",
        "∼": "tilde",
        "∽": "reversed tilde",
        "∾": "inverted lazy s",
        "∿": "sine wave",
        "≀": "wreath product",
        "≁": "not tilde",
        "≂": "minus tilde",
        "≃": "asymptotically equal",
        "≄": "not asymptotically equal",
        "≅": "approximately but not actually equal",
        "≆": "approximately but not equal",
        "≇": "neither approximately nor actually equal",
        "≉": "not almost equal",
        "≊": "almost equal or equal",
        "≋": "triple tilde",
        "≌": "all equal to",
        "≍": "equivalent to",
        "≎": "geometrically equivalent to",
        "≏": "difference between",
        "≐": "approaches the limit",
        "≑": "geometrically equal to",
        "≒": "approximately equal to or the image of",
        "≓": "image of or approximately equal to",
        "≔": "colon equals",
        "≕": "equals colon",
        "≖": "ring in equal to",
        "≗": "ring equal to",
        "≘": "corresponds to",
        "≙": "estimates",
        "≚": "equiangular to",
        "≛": "star equals",
        "≜": "delta equal to",
        "≝": "equal to by definition",
        "≞": "measured by",
        "≟": "questioned equal to",

        // Extended Latin
        À: "latin capital letter a with grave",
        Á: "latin capital letter a with acute",
        Â: "latin capital letter a with circumflex",
        Ã: "latin capital letter a with tilde",
        Ä: "latin capital letter a with diaeresis",
        Å: "latin capital letter a with ring above",
        Æ: "latin capital letter ae",
        Ç: "latin capital letter c with cedilla",
        È: "latin capital letter e with grave",
        É: "latin capital letter e with acute",
        Ê: "latin capital letter e with circumflex",
        Ë: "latin capital letter e with diaeresis",
        Ì: "latin capital letter i with grave",
        Í: "latin capital letter i with acute",
        Î: "latin capital letter i with circumflex",
        Ï: "latin capital letter i with diaeresis",
        Ð: "latin capital letter eth",
        Ñ: "latin capital letter n with tilde",
        Ò: "latin capital letter o with grave",
        Ó: "latin capital letter o with acute",
        Ô: "latin capital letter o with circumflex",
        Õ: "latin capital letter o with tilde",
        Ö: "latin capital letter o with diaeresis",
        Ø: "latin capital letter o with stroke",
        Ù: "latin capital letter u with grave",
        Ú: "latin capital letter u with acute",
        Û: "latin capital letter u with circumflex",
        Ü: "latin capital letter u with diaeresis",
        Ý: "latin capital letter y with acute",
        Þ: "latin capital letter thorn",
        ß: "latin small letter sharp s",
        à: "latin small letter a with grave",
        á: "latin small letter a with acute",
        â: "latin small letter a with circumflex",
        ã: "latin small letter a with tilde",
        ä: "latin small letter a with diaeresis",
        å: "latin small letter a with ring above",
        æ: "latin small letter ae",
        ç: "latin small letter c with cedilla",
        è: "latin small letter e with grave",
        é: "latin small letter e with acute",
        ê: "latin small letter e with circumflex",
        ë: "latin small letter e with diaeresis",
        ì: "latin small letter i with grave",
        í: "latin small letter i with acute",
        î: "latin small letter i with circumflex",
        ï: "latin small letter i with diaeresis",
        ð: "latin small letter eth",
        ñ: "latin small letter n with tilde",
        ò: "latin small letter o with grave",
        ó: "latin small letter o with acute",
        ô: "latin small letter o with circumflex",
        õ: "latin small letter o with tilde",
        ö: "latin small letter o with diaeresis",
        ø: "latin small letter o with stroke",
        ù: "latin small letter u with grave",
        ú: "latin small letter u with acute",
        û: "latin small letter u with circumflex",
        ü: "latin small letter u with diaeresis",
        ý: "latin small letter y with acute",
        þ: "latin small letter thorn",
        ÿ: "latin small letter y with diaeresis",

        // Symbols
        "¡": "inverted exclamation mark",
        "¿": "inverted question mark",

        // Arrows
        "←": "leftward arrow",
        "↑": "upward arrow",
        "→": "rightward arrow",
        "↓": "downward arrow",
        "↔": "left right arrow",
        "↕": "up down arrow",
        "↖": "north west arrow",
        "↗": "north east arrow",
        "↘": "south east arrow",
        "↙": "south west arrow",
        "↚": "leftward arrow with stroke",
        "↛": "rightward arrow with stroke",
        "↜": "leftward wave arrow",
        "↝": "rightward wave arrow",
        "↞": "leftward two headed arrow",
        "↟": "upward two headed arrow",
        "↠": "rightward two headed arrow",
        "↡": "downward two headed arrow",
        "↢": "leftward arrow with tail",
        "↣": "rightward arrow with tail",
        "↤": "leftward arrow from bar",
        "↥": "upward arrow from bar",
        "↦": "rightward arrow from bar",
        "↧": "downward arrow from bar",
        "↨": "up down arrow with base",
        "↩": "leftward arrow with hook",
        "↪": "rightward arrow with hook",
        "↫": "leftward arrow with loop",
        "↬": "rightward arrow with loop",
        "↭": "left right wave arrow",
        "↮": "left right arrow with stroke",
        "↯": "downward zigzag arrow",
        "↰": "upward arrow with tip leftward",
        "↱": "upward arrow with tip rightward",
        "↲": "downward arrow with tip leftward",
        "↳": "downward arrow with tip rightward",
        "↴": "rightward arrow with corner downward",
        "↵": "downward arrow with corner leftward",
        "↶": "anticlockwise top semicircle arrow",
        "↷": "clockwise top semicircle arrow",
        "↸": "north west arrow to long bar",
        "↹": "leftward arrow to bar over rightward arrow to bar",
        "↺": "anticlockwise open circle arrow",
        "↻": "clockwise open circle arrow",
        "↼": "leftward arrow with small circle",
        "↽": "upward arrow with small circle",
        "↾": "rightward arrow with small circle",
        "↿": "downward arrow with small circle",
        "⇀": "rightward arrow with small circle",
        "⇁": "downward arrow leftward of upward arrow",
        "⇂": "three rightward arrows",
        "⇃": "leftward arrow with vertical stroke",
        "⇄": "left right arrow with vertical stroke",
        "⇅": "up down arrow with horizontal stroke",
        "⇆": "leftward arrow with double vertical stroke",
        "⇇": "rightward arrow with double vertical stroke",
        "⇈": "downward arrow with horizontal stroke",
        "⇉": "upward arrow with horizontal stroke",
        "⇊": "upward arrow with double horizontal stroke",
        "⇋": "downward arrow with double horizontal stroke",
        "⇌": "left right double arrow with vertical stroke",
        "⇍": "leftward triple arrow",
        "⇎": "rightward triple arrow",
        "⇏": "leftward squiggle arrow",
        "⇐": "leftward double arrow",
        "⇑": "upward double arrow",
        "⇒": "rightward double arrow",
        "⇓": "downward double arrow",
        "⇔": "left right double arrow",
        "⇕": "up down double arrow",
        "⇖": "north west double arrow",
        "⇗": "north east double arrow",
        "⇘": "south east double arrow",
        "⇙": "south west double arrow",
        "⇚": "leftward arrow with stroke",
        "⇛": "rightward arrow with stroke",
        "⇜": "leftward wave arrow",
        "⇝": "rightward wave arrow",
        "⇞": "leftward two headed arrow",
        "⇟": "upward two headed arrow",
        "⇠": "rightward two headed arrow",
        "⇡": "downward two headed arrow",
        "⇢": "leftward arrow with tail",
        "⇣": "rightward arrow with tail",
        "⇤": "leftward arrow from bar",
        "⇥": "upward arrow from bar",
        "⇦": "rightward arrow from bar",
        "⇧": "downward arrow from bar",
        "⇨": "left right arrow with stroke",
        "⇩": "up down arrow with stroke",
        "⇪": "leftward arrow with vertical stroke",
        "⇫": "rightward arrow with vertical stroke",
        "⇬": "left right wave arrow",
        "⇭": "left right arrow with stroke",
        "⇮": "downward zigzag arrow",
        "⇯": "upward arrow with tip leftward",
        "⇰": "upward arrow with tip rightward",
        "⇱": "downward arrow with tip leftward",
        "⇲": "downward arrow with tip rightward",
        "⇴": "rightward arrow with corner downward",
        "⇵": "downward arrow leftward of upward arrow",
        "⇶": "three rightward arrows",
        "⇷": "leftward arrow with vertical stroke",
        "⇸": "rightward arrow with vertical stroke",
        "⇹": "leftward arrow with double vertical stroke",
        "⇺": "rightward arrow with double vertical stroke",
        "⇻": "leftward arrow with stroke",
        "⇼": "upward arrow with stroke",
        "⇽": "rightward arrow with stroke",
        "⇾": "downward arrow with stroke",
        "⇿": "up down arrow with stroke",
      };        
export { characterSets, type CharacterCategory , descriptions };