type EmojiCategory =
  | "all"
  | "symbols"
  | "people"
  | "animals-nature"
  | "food-drink"
  | "activity"
  | "travel-places"
  | "objects"
  | "flags";

const emojisSets: Record<EmojiCategory, { name: string; emojis: string[] }> = {
  all: {
    name: "All",
    emojis: [
      /* Symbols */
      "❤️",
      "💔",
      "💙",
      "💚",
      "💛",
      "🖤",
      "🤍",
      "🤎",
      "✔️",
      "❌",
      "☑️",
      "❗",
      "❓",
      "⚠️",
      "💯",
      "➕",
      "➖",
      "✖️",
      "➗",
      "♻️",
      "⚡",
      "🔥",
      "✨",
      "⭐",
      "⭕",
      "🚫",

      /* People */
      "😀",
      "😃",
      "😄",
      "😁",
      "😆",
      "😅",
      "😂",
      "🤣",
      "😊",
      "😇",
      "🙂",
      "🙃",
      "😉",
      "😍",
      "😘",
      "😎",
      "🤓",
      "😐",
      "😑",
      "😬",
      "🙄",
      "😏",
      "😌",
      "🤩",
      "🥳",
      "🤔",
      "😴",
      "😭",
      "😢",
      "😡",
      "🤯",
      "👍",
      "👎",
      "👌",
      "✌️",
      "🤞",
      "🙏",
      "👏",
      "🙌",
      "💪",

      /* Animals & Nature */
      "🐶",
      "🐱",
      "🐭",
      "🐹",
      "🐰",
      "🦊",
      "🐻",
      "🐼",
      "🐨",
      "🐯",
      "🦁",
      "🐮",
      "🐷",
      "🐸",
      "🐵",
      "🐔",
      "🐧",
      "🐦",
      "🦆",
      "🦅",
      "🦄",
      "🐝",
      "🦋",
      "🌲",
      "🌳",
      "🌴",
      "🌵",
      "🌸",
      "🌼",
      "🌻",
      "☀️",
      "🌙",
      "⭐",
      "🌈",
      "🌧️",
      "❄️",
      "🌊",

      /* Food & Drink */
      "🍎",
      "🍌",
      "🍉",
      "🍇",
      "🍓",
      "🍒",
      "🍍",
      "🥭",
      "🍐",
      "🍊",
      "🍋",
      "🍑",
      "🥝",
      "🥑",
      "🍔",
      "🍟",
      "🍕",
      "🌭",
      "🥪",
      "🌮",
      "🌯",
      "🍣",
      "🍜",
      "🍰",
      "🧁",
      "🍩",
      "🍪",
      "🍫",
      "☕",
      "🍵",
      "🥤",
      "🍺",
      "🍷",
      "🍸",
      "🍹",
      "🥂",

      /* Activity */
      "⚽",
      "🏀",
      "🏈",
      "⚾",
      "🎾",
      "🏐",
      "🏉",
      "🎮",
      "🎯",
      "🎳",
      "🎲",
      "♟️",
      "🏃",
      "🚴",
      "🏊",
      "🏋️",
      "🧘",
      "🎸",
      "🎹",
      "🥁",
      "🎺",
      "🎤",
      "🏆",
      "🥇",

      /* Travel & Places */
      "🚗",
      "🚕",
      "🚌",
      "🚎",
      "🚓",
      "🚑",
      "🚒",
      "✈️",
      "🚀",
      "🚁",
      "🚤",
      "🛳️",
      "🚢",
      "🏠",
      "🏢",
      "🏬",
      "🏫",
      "🏥",
      "🏰",
      "🗼",
      "🗽",
      "⛩️",
      "🕌",
      "🌍",
      "🌎",
      "🌏",
      "🏖️",
      "🏝️",

      /* Objects */
      "📱",
      "💻",
      "🖥️",
      "⌨️",
      "🖱️",
      "📷",
      "📸",
      "🎥",
      "📹",
      "📚",
      "📖",
      "📝",
      "📄",
      "📂",
      "🔒",
      "🔑",
      "🗝️",
      "💡",
      "🔦",
      "🕯️",
      "🧰",
      "🛠️",
      "🔧",
      "⚙️",
      "📦",
      "💳",
      "💰",
      "🔋",
      "🔌",

      /* Flags */
      "🇮🇳",
      "🇺🇸",
      "🇬🇧",
      "🇨🇦",
      "🇦🇺",
      "🇩🇪",
      "🇫🇷",
      "🇪🇸",
      "🇮🇹",
      "🇯🇵",
      "🇰🇷",
      "🇨🇳",
      "🇧🇷",
      "🇲🇽",
      "🇷🇺",
      "🇿🇦",
      "🇳🇿",
    ],
  },

  symbols: {
    name: "Symbols",
    emojis: [
      "❤️",
      "💔",
      "💙",
      "💚",
      "💛",
      "🖤",
      "🤍",
      "🤎",
      "✔️",
      "❌",
      "☑️",
      "❗",
      "❓",
      "⚠️",
      "💯",
      "➕",
      "➖",
      "✖️",
      "➗",
      "♻️",
      "⚡",
      "🔥",
      "✨",
      "⭐",
      "⭕",
      "🚫",
      "⬆️",
      "⬇️",
      "⬅️",
      "➡️",
      "🔄",
      "🔁",
      "🔀",
      "🔔",
      "🔕",
      "⏰",
      "⌛",
      "⏳",
    ],
  },

  people: {
    name: "People",
    emojis: [
      "😀",
      "😃",
      "😄",
      "😁",
      "😆",
      "😅",
      "😂",
      "🤣",
      "😊",
      "😇",
      "🙂",
      "🙃",
      "😉",
      "😍",
      "😘",
      "😎",
      "🤓",
      "😐",
      "😑",
      "😬",
      "🙄",
      "😏",
      "😌",
      "🤩",
      "🥳",
      "🤔",
      "😴",
      "😭",
      "😢",
      "😡",
      "🤯",
      "👍",
      "👎",
      "👌",
      "✌️",
      "🤞",
      "🙏",
      "👏",
      "🙌",
      "💪",
    ],
  },

  "animals-nature": {
    name: "Animals & Nature",
    emojis: [
      "🐶",
      "🐱",
      "🐭",
      "🐹",
      "🐰",
      "🦊",
      "🐻",
      "🐼",
      "🐨",
      "🐯",
      "🦁",
      "🐮",
      "🐷",
      "🐸",
      "🐵",
      "🐔",
      "🐧",
      "🐦",
      "🦆",
      "🦅",
      "🦄",
      "🐝",
      "🦋",
      "🌲",
      "🌳",
      "🌴",
      "🌵",
      "🌸",
      "🌼",
      "🌻",
      "☀️",
      "🌙",
      "⭐",
      "🌈",
      "🌧️",
      "❄️",
      "🌊",
    ],
  },

  "food-drink": {
    name: "Food & Drink",
    emojis: [
      "🍎",
      "🍌",
      "🍉",
      "🍇",
      "🍓",
      "🍒",
      "🍍",
      "🥭",
      "🍐",
      "🍊",
      "🍋",
      "🍑",
      "🥝",
      "🥑",
      "🍔",
      "🍟",
      "🍕",
      "🌭",
      "🥪",
      "🌮",
      "🌯",
      "🍣",
      "🍜",
      "🍰",
      "🧁",
      "🍩",
      "🍪",
      "🍫",
      "☕",
      "🍵",
      "🥤",
      "🍺",
      "🍷",
      "🍸",
      "🍹",
      "🥂",
    ],
  },

  activity: {
    name: "Activity",
    emojis: [
      "⚽",
      "🏀",
      "🏈",
      "⚾",
      "🎾",
      "🏐",
      "🏉",
      "🎮",
      "🎯",
      "🎳",
      "🎲",
      "♟️",
      "🏃",
      "🚴",
      "🏊",
      "🏋️",
      "🧘",
      "🎸",
      "🎹",
      "🥁",
      "🎺",
      "🎤",
      "🏆",
      "🥇",
      "🥈",
      "🥉",
    ],
  },

  "travel-places": {
    name: "Travel & Places",
    emojis: [
      "🚗",
      "🚕",
      "🚌",
      "🚎",
      "🚓",
      "🚑",
      "🚒",
      "✈️",
      "🚀",
      "🚁",
      "🚤",
      "🛳️",
      "🚢",
      "🏠",
      "🏢",
      "🏬",
      "🏫",
      "🏥",
      "🏰",
      "🗼",
      "🗽",
      "⛩️",
      "🕌",
      "🌍",
      "🌎",
      "🌏",
      "🏖️",
      "🏝️",
    ],
  },

  objects: {
    name: "Objects",
    emojis: [
      "📱",
      "💻",
      "🖥️",
      "⌨️",
      "🖱️",
      "📷",
      "📸",
      "🎥",
      "📹",
      "📚",
      "📖",
      "📝",
      "📄",
      "📂",
      "🔒",
      "🔑",
      "🗝️",
      "💡",
      "🔦",
      "🕯️",
      "🧰",
      "🛠️",
      "🔧",
      "⚙️",
      "📦",
      "💳",
      "💰",
      "🔋",
      "🔌",
    ],
  },

  flags: {
    name: "Flags",
    emojis: [
      "🇮🇳",
      "🇺🇸",
      "🇬🇧",
      "🇨🇦",
      "🇦🇺",
      "🇩🇪",
      "🇫🇷",
      "🇪🇸",
      "🇮🇹",
      "🇯🇵",
      "🇰🇷",
      "🇨🇳",
      "🇧🇷",
      "🇲🇽",
      "🇷🇺",
      "🇿🇦",
      "🇳🇿",
    ],
  },
};

const descriptions: Record<string, string> = {
  "💙": "blue heart",
  "💚": "green heart",
  "💛": "yellow heart",
  "🖤": "black heart",
  "🤍": "white heart",
  "🤎": "brown heart",
  "☑️": "check box with check",
  "🔴": "red circle",
  "🟢": "green circle",
  "🟡": "yellow circle",
  "🔵": "blue circle",
  "⬆️": "up arrow",
  "⬇️": "down arrow",
  "⬅️": "left arrow",
  "➡️": "right arrow",
  "🔄": "counterclockwise arrows",
  "🔁": "repeat button",
  "🔀": "shuffle tracks",
  "🔔": "bell",
  "🔕": "muted bell",
  "⏰": "alarm clock",
  "⏳": "hourglass not done",
  "⌛": "hourglass done",
  "♠️": "spade suit",
  "♥️": "heart suit",
  "♦️": "diamond suit",
  "♣️": "club suit",
  "🚫": "prohibited",
  "⭕": "hollow red circle",
  "❎": "cross mark button",

  "😐": "neutral face",
  "😑": "expressionless face",
  "😬": "grimacing face",
  "🙄": "face with rolling eyes",
  "😏": "smirking face",
  "😌": "relieved face",
  "🤩": "star struck",
  "😜": "winking face with tongue",
  "😝": "squinting face with tongue",
  "🤪": "zany face",
  "😢": "crying face sad",
  "😥": "sad but relieved face",
  "😓": "downcast face with sweat",
  "😱": "face screaming in fear",
  "😨": "fearful face",
  "🤗": "hugging face",
  "🤭": "face with hand over mouth",
  "🤫": "shushing face",
  "🤥": "lying face",
  "👌": "ok hand",
  "✌️": "victory hand",
  "🤞": "crossed fingers",
  "🙌": "raising hands",
  "💪": "flexed biceps",

  "🐔": "chicken",
  "🐧": "penguin",
  "🐦": "bird",
  "🐤": "baby chick",
  "🦆": "duck",
  "🦅": "eagle",
  "🐺": "wolf",
  "🦄": "unicorn",
  "🐝": "honeybee",
  "🐞": "lady beetle",
  "🦋": "butterfly",
  "🐢": "turtle",
  "🐍": "snake",
  "🦖": "t-rex",
  "🌿": "herb",
  "🍀": "four leaf clover",
  "🍁": "maple leaf",
  "🍂": "fallen leaf",
  "🌊": "water wave",
  "❄️": "snowflake",
  "☁️": "cloud",
  "⛈️": "cloud with lightning and rain",
  "🌪️": "tornado",

  "🍐": "pear",
  "🍊": "tangerine",
  "🍋": "lemon",
  "🍑": "peach",
  "🥝": "kiwi fruit",
  "🥑": "avocado",
  "🍆": "eggplant",
  "🌽": "ear of corn",
  "🥕": "carrot",
  "🥔": "potato",
  "🍞": "bread",
  "🥐": "croissant",
  "🥖": "baguette bread",
  "🧀": "cheese wedge",
  "🍖": "meat on bone",
  "🍗": "poultry leg",
  "🥩": "cut of meat",
  "🍦": "soft ice cream",
  "🍨": "ice cream",
  "🍫": "chocolate bar",
  "🍬": "candy",
  "🥛": "glass of milk",
  "🧃": "beverage box",
  "🍹": "tropical drink",
  "🥂": "clinking glasses",

  "🏓": "ping pong",
  "🥊": "boxing glove",
  "🥋": "martial arts uniform",
  "⛳": "flag in hole",
  "🏹": "bow and arrow",
  "🎿": "skis",
  "⛷️": "skier",
  "🏂": "snowboarder",
  "🎤": "microphone",
  "🎬": "clapper board",
  "🎨": "artist palette",
  "🧩": "puzzle piece",
  "🪀": "yo-yo",

  "🚇": "metro",
  "🚉": "station",
  "🚊": "tram",
  "🚝": "monorail",
  "🛻": "pickup truck",
  "🚐": "minibus",
  "🗺️": "world map",
  "🧭": "compass",
  "⛰️": "mountain",
  "🏔️": "snow capped mountain",
  "🌋": "volcano",
  "🏜️": "desert",
  "🏕️": "camping",
  "🏙️": "cityscape",
  "🌆": "city at dusk",
  "🌃": "night with stars",

  "📦": "package",
  "📫": "closed mailbox with raised flag",
  "📬": "open mailbox with raised flag",
  "📭": "open mailbox with lowered flag",
  "🧾": "receipt",
  "💳": "credit card",
  "💰": "money bag",
  "🪙": "coin",
  "🔋": "battery",
  "🔌": "electric plug",
  "🧯": "fire extinguisher",
  "🪜": "ladder",
  "🪞": "mirror",
  "🧹": "broom",
  "🧸": "teddy bear",

  /* Symbols */
  "❤️": "red heart love",
  "💔": "broken heart",
  "✔️": "check mark",
  "❌": "cross mark",
  "❗": "exclamation mark",
  "❓": "question mark",
  "⚠️": "warning",
  "💯": "hundred points",
  "➕": "plus sign",
  "➖": "minus sign",
  "✖️": "multiplication sign",
  "➗": "division sign",
  "♻️": "recycling symbol",
  "⚡": "high voltage",
  "🔥": "fire",
  "✨": "sparkles",
  "⭐": "star",

  /* Faces */
  "😀": "grinning face",
  "😃": "grinning face with big eyes",
  "😄": "grinning face with smiling eyes",
  "😁": "beaming face with smiling eyes",
  "😆": "grinning squinting face",
  "😅": "grinning face with sweat",
  "😂": "face with tears of joy lol",
  "🤣": "rolling on the floor laughing lol",
  "😊": "smiling face with smiling eyes smile happy",
  "😇": "smiling face with halo",
  "🙂": "slightly smiling face smile happy",
  "🙃": "upside-down face",
  "😉": "winking face",
  "😍": "smiling face with heart-eyes love",
  "😘": "face blowing a kiss",
  "😎": "smiling face with sunglasses cool",
  "🤓": "nerd face",
  "🥳": "partying face",
  "🤔": "thinking face",
  "😴": "sleeping face",
  "😭": "loudly crying face",
  "😡": "pouting face angry",
  "🤯": "exploding head",
  "👍": "thumbs up",
  "👎": "thumbs down",
  "🙏": "folded hands",
  "👏": "clapping hands",

  /* Animals */
  "🐶": "dog face",
  "🐱": "cat face",
  "🐭": "mouse face",
  "🐹": "hamster",
  "🐰": "rabbit face",
  "🦊": "fox",
  "🐻": "bear",
  "🐼": "panda",
  "🐨": "koala",
  "🐯": "tiger face",
  "🦁": "lion",
  "🐮": "cow face",
  "🐷": "pig face",
  "🐸": "frog",
  "🐵": "monkey face",

  /* Nature */
  "🌲": "evergreen tree",
  "🌳": "deciduous tree",
  "🌴": "palm tree",
  "🌵": "cactus",
  "🌸": "cherry blossom",
  "🌼": "blossom",
  "🌻": "sunflower",
  "☀️": "sun",
  "🌙": "crescent moon",
  "🌈": "rainbow",
  "🌧️": "cloud with rain",

  /* Food & Drink */
  "🍎": "red apple",
  "🍌": "banana",
  "🍉": "watermelon",
  "🍇": "grapes",
  "🍓": "strawberry",
  "🍒": "cherries",
  "🍍": "pineapple",
  "🥭": "mango",
  "🍔": "hamburger",
  "🍟": "french fries",
  "🍕": "pizza",
  "🌭": "hot dog",
  "🥪": "sandwich",
  "🌮": "taco",
  "🌯": "burrito",
  "🍣": "sushi",
  "🍜": "steaming bowl",
  "🍰": "shortcake",
  "🧁": "cupcake",
  "🍩": "doughnut",
  "🍪": "cookie",
  "☕": "hot beverage",
  "🍵": "teacup without handle",
  "🥤": "cup with straw",
  "🍺": "beer mug",
  "🍷": "wine glass",
  "🍸": "cocktail glass",

  /* Activity */
  "⚽": "soccer ball",
  "🏀": "basketball",
  "🏈": "american football",
  "⚾": "baseball",
  "🎾": "tennis",
  "🏐": "volleyball",
  "🏉": "rugby football",
  "🎮": "video game",
  "🎯": "direct hit",
  "🎳": "bowling",
  "🎲": "game die",
  "♟️": "chess pawn",
  "🏃": "person running",
  "🚴": "person biking",
  "🏊": "person swimming",
  "🏋️": "person lifting weights",
  "🧘": "person in lotus position",
  "🎸": "guitar",
  "🎹": "musical keyboard",
  "🥁": "drum",
  "🎺": "trumpet",
  "🏆": "trophy",
  "🥇": "gold medal",
  "🥈": "silver medal",
  "🥉": "bronze medal",

  /* Travel & Places */
  "🚗": "automobile",
  "🚕": "taxi",
  "🚌": "bus",
  "🚎": "trolleybus",
  "🚓": "police car",
  "🚑": "ambulance",
  "🚒": "fire engine",
  "✈️": "airplane",
  "🚀": "rocket",
  "🚁": "helicopter",
  "🚤": "speedboat",
  "🛳️": "passenger ship",
  "🚢": "ship",
  "🏠": "house",
  "🏢": "office building",
  "🏬": "department store",
  "🏫": "school",
  "🏥": "hospital",
  "🏰": "castle",
  "🗼": "tokyo tower",
  "🗽": "statue of liberty",
  "⛩️": "shinto shrine",
  "🕌": "mosque",
  "🌍": "globe showing europe-africa",
  "🌎": "globe showing americas",
  "🌏": "globe showing asia-australia",
  "🏖️": "beach with umbrella",
  "🏝️": "desert island",

  /* Objects */
  "📱": "mobile phone",
  "💻": "laptop",
  "🖥️": "desktop computer",
  "⌨️": "keyboard",
  "🖱️": "computer mouse",
  "📷": "camera",
  "📸": "camera with flash",
  "🎥": "movie camera",
  "📹": "video camera",
  "📚": "books",
  "📖": "open book",
  "📝": "memo",
  "📄": "page facing up",
  "📂": "open file folder",
  "🔒": "locked",
  "🔑": "key",
  "🗝️": "old key",
  "💡": "light bulb",
  "🔦": "flashlight",
  "🕯️": "candle",
  "🧰": "toolbox",
  "🛠️": "hammer and wrench",
  "🔧": "wrench",
  "⚙️": "gear",

  /* Flags */
  "🇮🇳": "flag: india",
  "🇺🇸": "flag: united states",
  "🇬🇧": "flag: united kingdom",
  "🇨🇦": "flag: canada",
  "🇦🇺": "flag: australia",
  "🇩🇪": "flag: germany",
  "🇫🇷": "flag: france",
  "🇪🇸": "flag: spain",
  "🇮🇹": "flag: italy",
  "🇯🇵": "flag: japan",
  "🇰🇷": "flag: south korea",
  "🇨🇳": "flag: china",
  "🇧🇷": "flag: brazil",
  "🇲🇽": "flag: mexico",
  "🇷🇺": "flag: russia",
  "🇿🇦": "flag: south africa",
  "🇳🇿": "flag: new zealand",
};

export { emojisSets, type EmojiCategory, descriptions };
